/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as RoomsCountryRouteImport } from './routes/rooms/$country'
import { Route as RoomIdRouteImport } from './routes/room/$id'
import { Route as DashboardPropertyIdIndexRouteImport } from './routes/dashboard/property/$id/index'
import { Route as DashboardPropertyIdEditRouteImport } from './routes/dashboard/property/$id/edit'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsCountryRoute = RoomsCountryRouteImport.update({
  id: '/rooms/$country',
  path: '/rooms/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomIdRoute = RoomIdRouteImport.update({
  id: '/room/$id',
  path: '/room/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPropertyIdIndexRoute =
  DashboardPropertyIdIndexRouteImport.update({
    id: '/dashboard/property/$id/',
    path: '/dashboard/property/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardPropertyIdEditRoute = DashboardPropertyIdEditRouteImport.update({
  id: '/dashboard/property/$id/edit',
  path: '/dashboard/property/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/room/$id': typeof RoomIdRoute
  '/rooms/$country': typeof RoomsCountryRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/property/$id/edit': typeof DashboardPropertyIdEditRoute
  '/dashboard/property/$id': typeof DashboardPropertyIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/room/$id': typeof RoomIdRoute
  '/rooms/$country': typeof RoomsCountryRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/property/$id/edit': typeof DashboardPropertyIdEditRoute
  '/dashboard/property/$id': typeof DashboardPropertyIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/room/$id': typeof RoomIdRoute
  '/rooms/$country': typeof RoomsCountryRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/property/$id/edit': typeof DashboardPropertyIdEditRoute
  '/dashboard/property/$id/': typeof DashboardPropertyIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/room/$id'
    | '/rooms/$country'
    | '/dashboard'
    | '/dashboard/property/$id/edit'
    | '/dashboard/property/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/room/$id'
    | '/rooms/$country'
    | '/dashboard'
    | '/dashboard/property/$id/edit'
    | '/dashboard/property/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/room/$id'
    | '/rooms/$country'
    | '/dashboard/'
    | '/dashboard/property/$id/edit'
    | '/dashboard/property/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  RoomIdRoute: typeof RoomIdRoute
  RoomsCountryRoute: typeof RoomsCountryRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPropertyIdEditRoute: typeof DashboardPropertyIdEditRoute
  DashboardPropertyIdIndexRoute: typeof DashboardPropertyIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$country': {
      id: '/rooms/$country'
      path: '/rooms/$country'
      fullPath: '/rooms/$country'
      preLoaderRoute: typeof RoomsCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$id': {
      id: '/room/$id'
      path: '/room/$id'
      fullPath: '/room/$id'
      preLoaderRoute: typeof RoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/property/$id/': {
      id: '/dashboard/property/$id/'
      path: '/dashboard/property/$id'
      fullPath: '/dashboard/property/$id'
      preLoaderRoute: typeof DashboardPropertyIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/property/$id/edit': {
      id: '/dashboard/property/$id/edit'
      path: '/dashboard/property/$id/edit'
      fullPath: '/dashboard/property/$id/edit'
      preLoaderRoute: typeof DashboardPropertyIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  RoomIdRoute: RoomIdRoute,
  RoomsCountryRoute: RoomsCountryRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPropertyIdEditRoute: DashboardPropertyIdEditRoute,
  DashboardPropertyIdIndexRoute: DashboardPropertyIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
